### ISSUE TITLE
Błędy.

### ISSUE THREAD

**Issue by DimitriCyka** [OtekPlay/OtekSectors#2]
Witam. Mam dosłownie 2 pytania. Czemu grupy zrobione są Hardcode https://github.com/OtekPlay/OtekSectors/blob/master/CoreSectorsPackets/src/main/java/pl/otekplay/sectors/enums/GroupType.java

**Comment by TheMolkaPL** [comment]
Widocznie plugin był pisany pod dany serwer. Można to rozwiązać obiektem `Group` i ładować go z bazy danych.

**Comment by OtekPlay** [comment]
To jest starsza wersja, tak byl pisany pod xHC plugin, mozna przerobic pod siebie, zalezalo mi bardziej abyscie zobaczyli w jaki sposob mozna zrobic sektory ;]
