### ISSUE TITLE
Jakie Jar'y

### ISSUE THREAD

**Issue by Urek00** [OtekPlay/OtekSectors#4]
Witam wklepałem ten plugin do Eclipsa a tu dupa. Są błedy i to w **uj błędów.

Trzeba do tego jakieś jar'y Czy jak?

**Comment by kamcio96** [comment]
Halo otek, napraf.

Mavena użyłeś?

**Comment by OtekPlay** [comment]
halo, juz powinno dzialac, sprawdz.

**Comment by TheMolkaPL** [comment]
Ogólnie trochę lipa bo projekt nie jest "zmavenizowany" - nie ma nigdzie pliku `pom.xml`. Wszystko musisz robić niestety na własną rękę...

**Comment by OtekPlay** [comment]
@TheMolkaPL shhh... troluuu

**Comment by kamcio96** [comment]
jak to projekt nie ma mavena, sam konfigurowałem te pomy XD To otek nie comitowal :wink:

**Comment by TheMolkaPL** [comment]
Może były na GitLabie ( ͡° ͜ʖ ͡°)

**Comment by OtekPlay** [comment]
( ͡° ͜ʖ ͡°)
